/**
 * This class is generated by jOOQ
 */
package jooqGen.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class Price extends org.jooq.impl.UpdatableTableImpl<jooqGen.tables.records.PriceRecord> {

	private static final long serialVersionUID = 155616079;

	/**
	 * The singleton instance of coin.price
	 */
	public static final jooqGen.tables.Price PRICE = new jooqGen.tables.Price();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<jooqGen.tables.records.PriceRecord> getRecordType() {
		return jooqGen.tables.records.PriceRecord.class;
	}

	/**
	 * The table column <code>coin.price.price_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<jooqGen.tables.records.PriceRecord, java.lang.Integer> PRICE_ID = createField("price_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>coin.price.code_id</code>
	 */
	public final org.jooq.TableField<jooqGen.tables.records.PriceRecord, java.lang.String> CODE_ID = createField("code_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>coin.price.reg_pgm_id</code>
	 */
	public final org.jooq.TableField<jooqGen.tables.records.PriceRecord, java.lang.String> REG_PGM_ID = createField("reg_pgm_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>coin.price.reg_timestamp</code>
	 */
	public final org.jooq.TableField<jooqGen.tables.records.PriceRecord, java.sql.Timestamp> REG_TIMESTAMP = createField("reg_timestamp", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The table column <code>coin.price.upd_pgm_id</code>
	 */
	public final org.jooq.TableField<jooqGen.tables.records.PriceRecord, java.lang.String> UPD_PGM_ID = createField("upd_pgm_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>coin.price.upd_timestamp</code>
	 */
	public final org.jooq.TableField<jooqGen.tables.records.PriceRecord, java.sql.Timestamp> UPD_TIMESTAMP = createField("upd_timestamp", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The table column <code>coin.price.volumn</code>
	 */
	public final org.jooq.TableField<jooqGen.tables.records.PriceRecord, java.lang.Double> VOLUMN = createField("volumn", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The table column <code>coin.price.market_cap</code>
	 */
	public final org.jooq.TableField<jooqGen.tables.records.PriceRecord, java.lang.Double> MARKET_CAP = createField("market_cap", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The table column <code>coin.price.price</code>
	 */
	public final org.jooq.TableField<jooqGen.tables.records.PriceRecord, java.lang.Double> PRICE_ = createField("price", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The table column <code>coin.price.circulating_supply</code>
	 */
	public final org.jooq.TableField<jooqGen.tables.records.PriceRecord, java.lang.Double> CIRCULATING_SUPPLY = createField("circulating_supply", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The table column <code>coin.price.percent_1_hour</code>
	 */
	public final org.jooq.TableField<jooqGen.tables.records.PriceRecord, java.lang.Double> PERCENT_1_HOUR = createField("percent_1_hour", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The table column <code>coin.price.percent_24_hour2</code>
	 */
	public final org.jooq.TableField<jooqGen.tables.records.PriceRecord, java.lang.Double> PERCENT_24_HOUR2 = createField("percent_24_hour2", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The table column <code>coin.price.percent_7_days</code>
	 */
	public final org.jooq.TableField<jooqGen.tables.records.PriceRecord, java.lang.Double> PERCENT_7_DAYS = createField("percent_7_days", org.jooq.impl.SQLDataType.DOUBLE, this);

	public Price() {
		super("price", jooqGen.Coin.COIN);
	}

	public Price(java.lang.String alias) {
		super(alias, jooqGen.Coin.COIN, jooqGen.tables.Price.PRICE);
	}

	@Override
	public org.jooq.Identity<jooqGen.tables.records.PriceRecord, java.lang.Integer> getIdentity() {
		return jooqGen.Keys.IDENTITY_PRICE;
	}

	@Override
	public org.jooq.UniqueKey<jooqGen.tables.records.PriceRecord> getMainKey() {
		return jooqGen.Keys.KEY_PRICE_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<jooqGen.tables.records.PriceRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<jooqGen.tables.records.PriceRecord>>asList(jooqGen.Keys.KEY_PRICE_PRIMARY);
	}

	@Override
	public jooqGen.tables.Price as(java.lang.String alias) {
		return new jooqGen.tables.Price(alias);
	}
}
