/**
 * This class is generated by jOOQ
 */
package generation.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class Coin extends org.jooq.impl.UpdatableTableImpl<generation.tables.records.CoinRecord> {

	private static final long serialVersionUID = -1306532834;

	/**
	 * The singleton instance of coin.coin
	 */
	public static final generation.tables.Coin COIN = new generation.tables.Coin();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<generation.tables.records.CoinRecord> getRecordType() {
		return generation.tables.records.CoinRecord.class;
	}

	/**
	 * The table column <code>coin.coin.coin_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<generation.tables.records.CoinRecord, java.lang.Integer> COIN_ID = createField("coin_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>coin.coin.reg_pgm_id</code>
	 */
	public final org.jooq.TableField<generation.tables.records.CoinRecord, java.lang.String> REG_PGM_ID = createField("reg_pgm_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>coin.coin.reg_timestamp</code>
	 */
	public final org.jooq.TableField<generation.tables.records.CoinRecord, java.sql.Timestamp> REG_TIMESTAMP = createField("reg_timestamp", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The table column <code>coin.coin.upd_pgm_id</code>
	 */
	public final org.jooq.TableField<generation.tables.records.CoinRecord, java.lang.String> UPD_PGM_ID = createField("upd_pgm_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>coin.coin.upd_timestamp</code>
	 */
	public final org.jooq.TableField<generation.tables.records.CoinRecord, java.sql.Timestamp> UPD_TIMESTAMP = createField("upd_timestamp", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The table column <code>coin.coin.name</code>
	 */
	public final org.jooq.TableField<generation.tables.records.CoinRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>coin.coin.code</code>
	 */
	public final org.jooq.TableField<generation.tables.records.CoinRecord, java.lang.String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>coin.coin.max_supply</code>
	 */
	public final org.jooq.TableField<generation.tables.records.CoinRecord, java.lang.Long> MAX_SUPPLY = createField("max_supply", org.jooq.impl.SQLDataType.BIGINT, this);

	public Coin() {
		super("coin", generation.Coin.COIN);
	}

	public Coin(java.lang.String alias) {
		super(alias, generation.Coin.COIN, generation.tables.Coin.COIN);
	}

	@Override
	public org.jooq.Identity<generation.tables.records.CoinRecord, java.lang.Integer> getIdentity() {
		return generation.Keys.IDENTITY_COIN;
	}

	@Override
	public org.jooq.UniqueKey<generation.tables.records.CoinRecord> getMainKey() {
		return generation.Keys.KEY_COIN_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<generation.tables.records.CoinRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<generation.tables.records.CoinRecord>>asList(generation.Keys.KEY_COIN_PRIMARY);
	}

	@Override
	public generation.tables.Coin as(java.lang.String alias) {
		return new generation.tables.Coin(alias);
	}
}
