/**
 * This class is generated by jOOQ
 */
package jooqGen;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>coin</code> 
 * schema
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class Keys {

	// IDENTITY definitions
	public static final org.jooq.Identity<jooqGen.tables.records.CoinRecord, java.lang.Integer> IDENTITY_COIN = Identities0.IDENTITY_COIN;
	public static final org.jooq.Identity<jooqGen.tables.records.PriceRecord, java.lang.Integer> IDENTITY_PRICE = Identities0.IDENTITY_PRICE;

	// UNIQUE and PRIMARY KEY definitions
	public static final org.jooq.UniqueKey<jooqGen.tables.records.CoinRecord> KEY_COIN_PRIMARY = UniqueKeys0.KEY_COIN_PRIMARY;
	public static final org.jooq.UniqueKey<jooqGen.tables.records.PriceRecord> KEY_PRICE_PRIMARY = UniqueKeys0.KEY_PRICE_PRIMARY;

	// FOREIGN KEY definitions

	/**
	 * No instances
	 */
	private Keys() {}

	@SuppressWarnings("hiding")
	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<jooqGen.tables.records.CoinRecord, java.lang.Integer> IDENTITY_COIN = createIdentity(jooqGen.tables.Coin.COIN, jooqGen.tables.Coin.COIN.COIN_ID);
		public static org.jooq.Identity<jooqGen.tables.records.PriceRecord, java.lang.Integer> IDENTITY_PRICE = createIdentity(jooqGen.tables.Price.PRICE, jooqGen.tables.Price.PRICE.PRICE_ID);
	}

	@SuppressWarnings({"hiding", "unchecked"})
	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<jooqGen.tables.records.CoinRecord> KEY_COIN_PRIMARY = createUniqueKey(jooqGen.tables.Coin.COIN, jooqGen.tables.Coin.COIN.COIN_ID);
		public static final org.jooq.UniqueKey<jooqGen.tables.records.PriceRecord> KEY_PRICE_PRIMARY = createUniqueKey(jooqGen.tables.Price.PRICE, jooqGen.tables.Price.PRICE.PRICE_ID);
	}
}
