/**
 * This class is generated by jOOQ
 */
package jooqGen;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in coin
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public final class Tables {

	/**
	 * The table coin.coin
	 */
	public static final jooqGen.tables.Coin COIN = jooqGen.tables.Coin.COIN;

	/**
	 * The table coin.price
	 */
	public static final jooqGen.tables.Price PRICE = jooqGen.tables.Price.PRICE;

	/**
	 * No instances
	 */
	private Tables() {}
}
